#pragma once

#include "Converter.h"

#define HYDRAULIC_ACTUATOR_MAXIMUM_POSITION 1
#define HYDRAULIC_ACTUATOR_MINIMUM_POSITION -1
#define HYDRAULIC_ACTUATOR_INITIAL_POSITION 0

#define HYDRAULIC_PISTON_MAXIMUM_POSITION convert_millimeters_to_nanometers(50)
#define HYDRAULIC_PISTON_MINIMUM_POSITION 0
#define HYDRAULIC_PISTON_INITIAL_POSITION 0
