#pragma once

#define REMOTE_PIN_CHANNEL_1 13
#define REMOTE_PIN_CHANNEL_2 12
#define REMOTE_PIN_CHANNEL_3 11
#define REMOTE_PIN_CHANNEL_4 10
#define REMOTE_PIN_CHANNEL_5 9
#define REMOTE_PIN_CHANNEL_6 8
